### ISSUE TITLE
Data Requests are not rendered but return a 404 by S3.

### ISSUE THREAD

**Issue by csenk** [serverless-nextjs/serverless-next.js#615]
**Describe the bug**
We use SSR enabled by getServerSideProps in our project. In one of our staging environments we see that by navigating from page A to B the entire SPA is reloaded because the data request (/_next/data/-KIgsV04oYrYBKJBEr1YE/some-path.json?some=parameter) returns a 404.

**Expected behavior**
Data Requests do not return a 404 code.

**Desktop (please complete the following information):**

- OS: MacOS 
- Version 10.14.2

**Additional context**
We had a look into it and were able to find the issue.
```
S3Check: if (isPublicFile ||
        (isHTMLPage && !isPreviewRequest) ||
        (hasFallback && !isPreviewRequest) ||
        (isDataReq && !isPreviewRequest)) {
        if (isHTMLPage || hasFallback) {
            s3Origin.path = `${routesManifest_json.basePath}/static-pages`;
            const pageName = uri === "/" ? "/index" : uri;
            request.uri = `${pageName}.html`;
        }
        if (isPublicFile) {
            s3Origin.path = `${routesManifest_json.basePath}/public`;
            if (routesManifest_json.basePath) {
                request.uri = request.uri.replace(routesManifest_json.basePath, "");
            }
        }
        if (isDataReq) {
            // We need to check whether data request is unmatched i.e routed to 404.html or _error.js
            const pagePath = router(manifest)(uri);
            if (pagePath === "pages/404.html") {
                // Request static page from s3
                s3Origin.path = `${routesManifest_json.basePath}/static-pages`;
                request.uri = pagePath.replace("pages", "");
            }
            else if (pagePath === "pages/_error.js") {
                // Break to continue to SSR render _error.js
                break S3Check;
            }
            // By breaking to S3Check for all data requests except those matching a 404 we could fix it 
        }
        addS3HostHeader(request, normalisedS3DomainName);
        return request;
    }
```
By breaking to S3Check for all data requests except those matching a 404 we could fix it.
Can we do anything to help you fix this issue?

**Comment by dphang** [comment]
Thanks for reporting!  I see, I thought data requests here should always be served from S3, except if it's unmatched then it serves the 404 pages or _error.js page.

Do you have a simple repro and/or PR you can share? I can try it out and fix.

**Comment by dphang** [comment]
Published in `@sls-next/serverless-component@1.17.0-alpha.16`, please let me know if this is fixed for you.

**Comment by csenk** [comment]
Hey, I wanted to prepare a dedicated example to reproduce this issue and figured out that this problem did not occur. The reason is exactly as you say: the origin-request handler passes the request down to the s3. The S3 has to be configured to answer with a 403, so that the origin-response handler in return is able to catch this and render the data-request at that point.

It was a little confusing for me to see that the data-request is actually rendered in the origin-response handler, not in the origin-request handler.

The issue on our side, was that the S3 returned a 404, not 403 because our bucket policy was slightly misconfigured.

Thanks to you for having such a quick look into it.
I apologise for the inconvenience I caused with the issue.

**Comment by dphang** [comment]
Yeah no problem, it helped catch a related bug anyway which I fixed, so that was helpful! We shouldn't even be trying to go to S3 origin for SSR data requests, as the file would not exist in the S3 bucket.

Closing this issue - please open another if you find other issues.

**Comment by karthikeyan676** [comment]
Hi, it seems like the issue still exists. I'm currently using 1.19.0-alpha.28 version but the issue still there.

**Comment by dphang** [comment]
@karthikeyan676 please open new issue with more details and a repro if possible
